import './service-cards.css';
import {serviceTemplates} from './service-templates.js';
import './styles.css';import './portal.css';
import {api,session,logout,node} from './session.js';
const status=document.querySelector('#admin-status');let services=[],editing=null,offset=0;
const money=new Intl.NumberFormat('ru-RU'), date=new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Moscow'});
const temperatures={hot:'Высокий · горячий',warm:'Средний · тёплый',cold:'Низкий · холодный'};
function report(e){status.textContent=e.message;if(e.status===401){document.querySelector('#admin-content').hidden=true;document.querySelector('#admin-gate').hidden=false;document.querySelector('#admin-gate p').textContent='Сессия завершена. Войдите снова.';}}
function button(text,fn,cls='table-action'){const b=node('button',text,cls);b.type='button';b.addEventListener('click',fn);return b;}
function cell(text){return node('td',text)}
async function loadServices(){services=await api('/api/admin/services');const body=document.querySelector('#service-rows');body.replaceChildren();for(const s of services){const tr=node('tr');const title=cell('');title.append(node('strong',s.name),node('small',s.slug));const actions=cell('');actions.append(button('Редактировать',()=>edit(s)),button('Удалить',()=>remove(s),'table-action danger'));tr.append(title,cell(`${money.format(s.price_min)}–${money.format(s.price_max)}`),cell(!s.active?'Скрыта':s.prices_approved?'Услуга и цены':'Услуга · цены скрыты'),actions);body.append(tr);}if(!services.length)status.textContent='Каталог пуст. Добавьте первую услугу.';}
function edit(s=null){editing=s?.id||null;const f=document.querySelector('#service-editor');f.reset();for(const name of ['name','slug','description','price_min','price_max','price_review_note','delivery_time','public_note','button_text'])f.elements[name].value=s?.[name]??'';f.elements.scope_items.value=(s?.scope_items||[]).join('\n');f.elements.button_text.value=s?.button_text||'Обсудить проект';document.querySelector('#service-template').value=serviceTemplates[s?.slug]?s.slug:'';for(const name of ['active','prices_approved'])f.elements[name].checked=s?s[name]:name==='active';document.querySelector('#editor-title').textContent=s?'Редактировать услугу':'Новая услуга';document.querySelector('#editor-status').textContent='';document.querySelector('#service-dialog').showModal();}
async function remove(s){if(!confirm(`Удалить «${s.name}» из каталога? Существующие заявки сохранятся.`))return;try{await api('/api/services/'+s.id,{method:'DELETE'});await loadServices();status.textContent='Услуга удалена из каталога и с главной страницы.';}catch(e){report(e)}}
document.querySelector('#add-service').addEventListener('click',()=>edit());
document.querySelector('#service-editor').addEventListener('submit',async e=>{e.preventDefault();const f=e.target;if(!f.reportValidity())return;const b=document.querySelector('#save-service');b.disabled=true;const d=new FormData(f);const payload={name:d.get('name'),slug:d.get('slug'),description:d.get('description'),scope_items:d.get('scope_items').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),delivery_time:d.get('delivery_time'),public_note:d.get('public_note'),button_text:d.get('button_text'),price_min:Number(d.get('price_min')),price_max:Number(d.get('price_max')),active:d.get('active')==='on',prices_approved:d.get('prices_approved')==='on',price_review_note:d.get('price_review_note')};try{await api('/api/services'+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify(payload)});document.querySelector('#service-dialog').close();await loadServices();status.textContent='Услуга сохранена.';}catch(error){document.querySelector('#editor-status').textContent=error.message;}finally{b.disabled=false}});
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>document.getElementById(b.dataset.close).close());
async function loadLeads(){const rows=await api(`/api/admin/requests?limit=25&offset=${offset}&include_test=${document.querySelector('#include-test').checked}`);const body=document.querySelector('#lead-rows');body.replaceChildren();for(const r of rows){const a=r.assessment,tr=node('tr'),badge=node('span',a?`${temperatures[a.temperature]} / ${a.score}`:'Не оценена','badge '+(a?.temperature||''));const priority=cell('');priority.append(badge);if(a?.is_test)priority.append(node('small','ТЕСТ'));const who=cell('');who.append(node('strong',r.name),node('small',r.email));const actions=cell('');actions.append(button('Просмотр',()=>viewLead(r.id)));tr.append(priority,who,cell(r.service_name),cell(date.format(new Date(r.created_at))),actions);body.append(tr);}document.querySelector('#leads-prev').disabled=offset===0;document.querySelector('#leads-next').disabled=rows.length<25;document.querySelector('#leads-page').textContent=`Страница ${offset/25+1} · ${rows.length} заявок`}
async function viewLead(id){try{const r=await api('/api/admin/requests/'+id),a=r.assessment,box=document.querySelector('#lead-detail');box.replaceChildren();for(const [label,value]of [['Номер',r.id],['Имя',r.name],['Email',r.email],['Компания',r.company||'—'],['Услуга',r.service_name],['Получена',date.format(new Date(r.created_at))+' МСК'],['Бюджет',a?.budget==null?'Не указан':money.format(a.budget)+' ₽'],['Задача',r.message]]){box.append(node('h3',label),node('p',value));}box.append(node('h3','Оценка приоритета'));box.append(node('p',a?`${temperatures[a.temperature]} · ${a.score}/100 · правило ${a.rule_version}`:'Заявка создана до системы оценки.'));for(const reason of a?.reasons||[])box.append(node('p',`+${reason.points} — ${reason.reason}`));box.append(node('p','Это правило сортировки для менеджера, а не прогноз покупки.','muted'));document.querySelector('#lead-dialog').showModal();}catch(e){report(e)}}
for(const id of ['refresh-leads','include-test'])document.getElementById(id).addEventListener(id==='include-test'?'change':'click',()=>{offset=0;loadLeads().catch(report)});
document.querySelector('#leads-prev').addEventListener('click',()=>{offset=Math.max(0,offset-25);loadLeads().catch(report)});document.querySelector('#leads-next').addEventListener('click',()=>{offset+=25;loadLeads().catch(report)});
function duration(s){return `${Math.floor(s/60)} мин ${Math.round(s%60)} с`}
async function loadMetrics(){const q=new URLSearchParams({period:document.querySelector('#metric-period').value,device:document.querySelector('#metric-device').value,kind:document.querySelector('#metric-kind').value});const d=await api('/api/admin/metrics?'+q);const cards=document.querySelector('#metric-cards');cards.replaceChildren();for(const [key,label]of [['day','Сегодня'],['week','Эта неделя'],['month','Этот месяц']]){const card=node('article','','stat-card');card.append(node('span',label),node('strong',duration(d.averages[key].average_seconds)),node('small',`${d.averages[key].visits} посещений`));cards.append(card)}const canvas=document.querySelector('#heatmap'),ctx=canvas.getContext('2d');ctx.fillStyle='#111819';ctx.fillRect(0,0,640,800);ctx.strokeStyle='#273234';ctx.fillStyle='#94a2a1';ctx.font='12px sans-serif';for(let i=0;i<=10;i++){const x=35+i*58,y=25+i*74;ctx.beginPath();ctx.moveTo(x,25);ctx.lineTo(x,765);ctx.stroke();ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(615,y);ctx.stroke();ctx.fillText(i*10+'%',x-10,790);ctx.fillText(i*10+'%',0,y+4);}const max=Math.max(1,...d.heatmap.map(p=>p.count));for(const p of d.heatmap){const x=35+p.x*580,y=25+p.y*740,g=ctx.createRadialGradient(x,y,0,x,y,18);g.addColorStop(0,`rgba(220,248,123,${.3+.7*p.count/max})`);g.addColorStop(1,'rgba(124,220,170,0)');ctx.fillStyle=g;ctx.fillRect(x-18,y-18,36,36);}document.querySelector('#heatmap-caption').textContent=d.heatmap.length?`${d.visits} посещений · ярче = больше событий · максимум ${max} в ячейке`:'Пока нет событий для выбранного периода и экрана.';const clicks=document.querySelector('#click-stats');clicks.replaceChildren();const labels={navigation:'Навигация',service:'Услуги',brief:'Переход к заявке',submit:'Отправка формы',auth:'Аккаунт',form:'Элементы формы',other:'Другие элементы'};for(const [k,n]of Object.entries(d.clicks).sort((a,b)=>b[1]-a[1])){const p=node('p','','click-row');p.append(node('span',labels[k]||k),node('strong',String(n)));clicks.append(p)}document.querySelector('#metric-note').textContent=d.note;}
for(const id of ['metric-period','metric-device','metric-kind'])document.getElementById(id).addEventListener('change',()=>loadMetrics().catch(report));document.querySelector('#refresh-metrics').addEventListener('click',()=>loadMetrics().catch(report));
for(const b of document.querySelectorAll('[data-tab]'))b.addEventListener('click',async()=>{for(const t of ['services','leads','metrics'])document.querySelector('#tab-'+t).hidden=t!==b.dataset.tab;for(const n of document.querySelectorAll('[data-tab]'))n.classList.toggle('selected',n===b);document.querySelector('#page-title').textContent={services:'Услуги',leads:'Заявки',metrics:'Статистика пользователей'}[b.dataset.tab];status.textContent='';try{await({services:loadServices,leads:loadLeads,metrics:loadMetrics}[b.dataset.tab])()}catch(e){report(e)}});
document.querySelector('#admin-logout').addEventListener('click',()=>logout().catch(report));
session().then(async s=>{if(!s||s.user.role!=='admin'){document.querySelector('#admin-gate p').textContent=s?'Этому аккаунту не назначена роль администратора.':'Войдите в аккаунт администратора.';return}document.querySelector('#admin-email').textContent=s.user.email;document.querySelector('#admin-gate').hidden=true;document.querySelector('#admin-content').hidden=false;await loadServices()}).catch(report);

document.querySelector('#apply-service-template').addEventListener('click',()=>{
  const key=document.querySelector('#service-template').value, template=serviceTemplates[key];
  if(!template)return;
  const form=document.querySelector('#service-editor');
  for(const [name,value] of Object.entries(template)) {
    if(editing && (name==='name'||name==='slug'))continue;
    form.elements[name].value=Array.isArray(value)?value.join('\n'):value;
  }
  form.elements.prices_approved.checked=false;
  form.elements.price_review_note.value='';
  document.querySelector('#editor-status').textContent='Шаблон заполнен. Проверьте объём, сроки и цены; для их публикации включите галочку «Цены проверены…» и сохраните услугу.';
});
