#!/usr/bin/env bash
set -Eeuo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"
load_env() {
  [[ -f .env ]] || { echo 'Сначала выполните bash scripts/init-env.sh' >&2; exit 1; }
  # This file is locally generated by init-env.sh and owned by the server operator.
  set -a
  source .env
  set +a
  [[ "$DOMAIN" =~ ^[a-z0-9]([a-z0-9.-]*[a-z0-9])?$ ]] || { echo 'Некорректный DOMAIN' >&2; exit 1; }
}
require_root() { [[ $EUID -eq 0 ]] || { echo 'Запустите от root.' >&2; exit 1; }; }
